name: "H5"
department: "F4"
periodOfAppointmentFrom: "J6"
periodOfAppointmentTo: "N6"
periodofExtensionFrom: "J7"
extensionPrefix: "C7"
extensionSufix: "M7"
periodofExtensionTo: "N7"
employeeIDPrefix: "N5"
employeeID: "O5"
bankBranch: "AA4"
accountNumber: "Y5"
ifscCode: "Y6"
mobileNumber: "Y7"
firstHalfColumn: "H9"
secondHalfColumn: "X9"
mainCertififcate: "B16"
holidayCertififcate: "B22"
anRowNumber: "11"
fnRowNumber: "12"
dateColumnMapping:
  21: "C"
  22: "D"
  23: "E"
  24: "F"
  25: "G"
  26: "H"
  27: "I"
  28: "J"
  29: "K"
  30: "L"
  31: "M"
  1: "N"
  2: "O"
  3: "P"
  4: "Q"
  5: "R"
  6: "S"
  7: "T"
  8: "U"
  9: "V"
  10: "W"
  11: "X"
  12: "Y"
  13: "Z"
  14: "AA"
  15: "AB"
  16: "AC"
  17: "AD"
  18: "AE"
  19: "AF"
  20: "AG"
datasheet_nameCellID: "B1"
datasheet_post_designationCellID: "B2"
datasheet_mobileNum: "B3"
datasheet_bank_branch: "B4"
datasheet_accountNum: "B5"
datasheet_ifscCode: "B6"
datasheet_employeeID: "B7"
