name: "G5"
department: "E4"
periodOfAppointmentFrom: "I6"
periodOfAppointmentTo: "M6"
periodofExtensionFrom: "I7"
extensionPrefix: "B7"
extensionSufix: "L7"
periodofExtensionTo: "M7"
employeeIDPrefix: "M5"
employeeID: "N5"
bankBranch: "Z4"
accountNumber: "X5"
ifscCode: "X6"
mobileNumber: "X7"
firstHalfColumn: "G10"
secondHalfColumn: "G15"
mainCertififcate: "A21"
holidayCertififcate: "A26"
anRowNumberFirstMonth: "12"
fnRowNumberFirstMonth: "13"
anRowNumberSecondMonth: "17"
fnRowNumberSecondMonth: "18"
dateColumnMapping:
  21: "V"
  22: "W"
  23: "X"
  24: "Y"
  25: "Z"
  26: "AA"
  27: "AB"
  28: "AC"
  29: "AD"
  30: "AE"
  31: "AF"
  1: "B"
  2: "C"
  3: "D"
  4: "E"
  5: "F"
  6: "G"
  7: "H"
  8: "I"
  9: "J"
  10: "K"
  11: "L"
  12: "M"
  13: "N"
  14: "O"
  15: "P"
  16: "Q"
  17: "R"
  18: "S"
  19: "T"
  20: "U"
datasheet_nameCellID: "B1"
datasheet_post_designationCellID: "B2"
datasheet_mobileNum: "B3"
datasheet_bank_branch: "B4"
datasheet_accountNum: "B5"
datasheet_ifscCode: "B6"
datasheet_employeeID: "B7"
